database:
  username: root
  password: root
  url: jdbc:mysql://localhost:3306/bank

jwt:
  secret: 20!40709272Rr@02092025
  expiration: 30000
  issuer: bank

gateway:
  keystore:
    path: C:/Users/raksh/OneDrive/Desktop/complete-java/certificates/gateway-keystore.p12
    password: R@kshith1
  truststore:
    path: C:/Users/raksh/OneDrive/Desktop/complete-java/certificates/gateway-truststore.p12
    password: R@kshith1

users:
  keystore:
    path: C:/Users/raksh/OneDrive/Desktop/complete-java/certificates/userservice-keystore.p12
    password: R@kshith1
  truststore:
    path: C:/Users/raksh/OneDrive/Desktop/complete-java/certificates/userservice-truststore.p12
    password: R@kshith1
