spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8080/
  cloud:
    config:
      uri: http://localhost:8080
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 10