server:
  port: 8081
  ssl:
    enabled: true
    client-auth: need
    key-store: ${accounts.keystore.path}
    key-store-password: ${accounts.keystore.password}
    trust-store: ${accounts.truststore.path}
    trust-store-password: ${accounts.truststore.password}

eureka:
  instance:
    prefer-ip-address: true
    secure-port-enabled: true
    secure-port: ${server.port}
    non-secure-port-enabled: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/