server:
  port: 8081
  ssl:
    enabled: true
    client-auth: need
    key-store: ${accounts.keystore.path}
    key-store-password: ${accounts.keystore.password}
    trust-store: ${accounts.truststore.path}
    trust-store-password: ${accounts.truststore.password}

spring:
  config:
    import:
      - eureka-config.yml
      - database-config.yml