server:
  port: 8082
  ssl:
    enabled: true
    client-auth: need
    key-store: ${auth.keystore.path}
    key-store-password: ${auth.keystore.password}
    trust-store: ${auth.truststore.path}
    trust-store-password: ${auth.truststore.password}


spring:
  config:
    import:
      - eureka-config.yml
      - security-config.yml
      - database-config.yml
