server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/account/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**,/public/auth/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**,/public/users/**