server:
  port: 8083
  ssl:
    enabled: true
    client-auth: want
    key-store: ${gateway.keystore.path}
    key-store-password: ${gateway.keystore.password}
    trust-store: ${gateway.truststore.path}
    trust-store-password: ${gateway.truststore.password}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/account/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/public/auth/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**,/api/public/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    secure-port-enabled: true
    secure-port: ${server.port}
    non-secure-port-enabled: false