server:
  port: 8083
  ssl:
    enabled: true
    client-auth: want
    key-store: ${gateway.keystore.path}
    key-store-password: ${gateway.keystore.password}
    trust-store: ${gateway.truststore.path}
    trust-store-password: ${gateway.truststore.password}

spring:
  config:
    import:
      - eureka-config.yml
      - security-config.yml
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/account/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/public/auth/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**,/api/public/users/**
