server:
  port: 8084
  ssl:
    enabled: true
    client-auth: need
    key-store: ${users.keystore.path}
    key-store-password: ${users.keystore.password}
    trust-store: ${users.truststore.path}
    trust-store-password: ${users.truststore.password}

spring:
  config:
    import:
      - eureka-config.yml
      - database-config.yml
      - swagger-config.yml
  application:
    name: user-service
    jpa:
      hibernate:
        ddl-auto: update
